config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :categories
  end
  resources :ideas
  resources :users

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true

  belongs_to :category 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, presence: true,
                       uniqueness: true

  enum role: %w(default admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
   current_user && current_user.admin?
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def index
    @ideas = Idea.all
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(idea_params)
    if @idea.save
      redirect_to idea_path(@idea)
    else
      render :new
    end
  end

  def show
    @idea = Idea.find(params[:id])
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])
    if @idea.update(idea_params)
      redirect_to idea_path(@idea)
    else
      render :edit
    end
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy
    redirect_to ideas_path
  end

private

  def idea_params
    params.require(:idea).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:notice] = "Login successful"
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
  end

private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h1>Admin Homepage</h1>

app/views/ideas/_form.html.erb
<%= form_for @idea do |f| %>

<%= f.label :title %>
<%= f.text_field :title %> <br>

<%= f.label :content %>
<%= f.text_area :content %>

<%= f.submit %>
<% end %>

app/views/ideas/edit.html.erb
<h1>Edit Idea</h1>

<%= render partial: "form" %>

app/views/ideas/index.html.erb
<h1>Idea List</h1>

<%= @ideas.each do |idea| %>
<%= link_to idea.title, idea_path(idea) %>
<% end %>

<%= link_to "New Idea", new_idea_path %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render partial: "form" %>

app/views/ideas/show.html.erb
<h1>Idea: <%= @idea.title %></h1>

<p>
  <%= @idea.content %>
</p>
<%= link_to "Edit Idea", edit_idea_path(@idea) %>
<%= link_to "Delete Idea", idea_path(@idea), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ideabox</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    Welcome, <%= current_user.username %>
    <%= link_to "Logout", logout_path, method: :delete %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Create a New Account</h1>

<%= form_for @user do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %> <br>

  <%= f.label :password %>
  <%= f.text_field :password %> <br>

  <%= f.submit  "Create Account"%>
<% end %>